"""
phoneburner_push.py — Push contacts directly to PhoneBurner via API.

Usage:
    python main.py --phoneburner-push [--dry-run]

Same inclusion criteria as the CSV export:
  - equity_signal IN (🏆, ✅)
  - sale_date between today+5 and today+30
  - directskip_date populated
  - not cancelled

Creates a dated folder "Eagle Creek YYYY-MM-DD" in PhoneBurner, then pushes
one contact per DirectSkip person with all available phones (up to 5).
Custom notes include Auction Date, Primary Owner, and Relation.

Requires: PHONEBURNER_ACCESS_TOKEN in .env
"""

from __future__ import annotations

import os
import time
from datetime import date, timedelta

import requests
from dotenv import load_dotenv

from db import _conn

load_dotenv()

BASE_URL = "https://www.phoneburner.com/rest/1"


# ── API helper ────────────────────────────────────────────────────────────────

def _api(method: str, route: str, **kwargs) -> dict:
    """Make an authenticated API call. Raises on non-2xx."""
    token = os.environ.get("PHONEBURNER_ACCESS_TOKEN", "")
    if not token:
        raise RuntimeError("PHONEBURNER_ACCESS_TOKEN is not set in .env")
    headers = kwargs.pop("headers", {})
    headers["Authorization"] = f"Bearer {token}"
    resp = requests.request(
        method,
        f"{BASE_URL}/{route.lstrip('/')}",
        headers=headers,
        **kwargs,
    )
    if not resp.ok:
        raise RuntimeError(
            f"PhoneBurner API error {resp.status_code} on {method} /{route}: {resp.text[:400]}"
        )
    if resp.status_code == 204 or not resp.content:
        return {}
    return resp.json()


# ── Account helpers ───────────────────────────────────────────────────────────

def _get_member_id() -> str | None:
    """Return the first member user_id on the account (single-user setup)."""
    try:
        data = _api("GET", "members")
        # Response: {"members": {"total_results": N, "members": [...]}}
        members_block = data.get("members", {})
        if isinstance(members_block, dict):
            members_list = members_block.get("members", [])
        else:
            members_list = members_block  # fallback if it's already a list
        if members_list:
            m = members_list[0]
            return m.get("member_user_id") or m.get("user_id") or m.get("id")
    except Exception as e:
        print(f"  [PB] Warning: could not fetch member ID — {e}")
    return None


def _create_folder(name: str) -> str | None:
    """Create a contact folder and return its ID."""
    data = _api("POST", "folders", json={
        "name": name,
        "description": "Auto-generated by Eagle Creek Auction Monitor",
    })
    # Response: {"folders": {"0": {"id": "...", "folder_id": "...", "folder_name": "..."}}}
    folders = data.get("folders", {})
    first = folders.get("0", {}) if isinstance(folders, dict) else {}
    return str(first.get("id") or first.get("folder_id") or "")


def _find_folder(name: str) -> str | None:
    """Return folder ID if a folder with this name already exists, else None."""
    data = _api("GET", "folders")
    folders = data.get("folders", {})
    # Response: {"folders": {"0": {...}, "1": {...}}} — dict with numeric string keys
    items = folders.values() if isinstance(folders, dict) else folders
    for f in items:
        if not isinstance(f, dict):
            continue
        if f.get("folder_name", "").strip() == name:
            return str(f.get("id") or f.get("folder_id"))
    return None


def _get_or_create_folder(name: str) -> int | None:
    """Return existing folder ID or create a new one."""
    folder_id = _find_folder(name)
    if folder_id:
        print(f"  [PB] Using existing folder: '{name}' (id={folder_id})")
        return folder_id
    folder_id = _create_folder(name)
    print(f"  [PB] Created folder: '{name}' (id={folder_id})")
    return folder_id


# ── Contact push ──────────────────────────────────────────────────────────────

def _push_contact(
    row: dict,
    member_id: str | None,
    folder_id: str | None,
) -> str:
    """
    Create one PhoneBurner contact from a DB row, then add extra phones
    via the phones sub-resource.  Returns the new contact's user_id.
    """
    # Collect non-empty phones
    phones = [
        (row["phone1"] or "").strip(),
        (row["phone2"] or "").strip(),
        (row["phone3"] or "").strip(),
        (row["phone4"] or "").strip(),
        (row["phone5"] or "").strip(),
    ]
    phones = [p for p in phones if p]

    primary_phone = phones[0] if phones else ""
    extra_phones  = phones[1:]

    primary_owner = (
        f"{row['primary_first'] or ''} {row['primary_last'] or ''}".strip()
    )
    auction_date = _format_date(row["sale_date"])

    notes = (
        f"Relation: Owner | "
        f"Primary Owner: {primary_owner} | "
        f"Auction Date: {auction_date} | "
        f"Property: {row['street'] or ''}, {row['city'] or ''}, "
        f"{row['state'] or ''} {row['zip'] or ''}"
    ).strip()

    # Create the contact with primary phone and address
    payload: list[tuple[str, str]] = [
        ("first_name", (row["first_name"] or "").strip()),
        ("last_name",  (row["last_name"]  or "").strip()),
        ("phone",      primary_phone),
        ("address1",   (row["street"] or "").strip()),
        ("city",       (row["city"]   or "").strip()),
        ("state",      (row["state"]  or "").strip()),
        ("zip",        (row["zip"]    or "").strip()),
        ("notes",      notes),
    ]
    if folder_id:
        payload.append(("category_id", str(folder_id)))
    if member_id:
        payload.append(("owner_id", str(member_id)))

    resp = _api("POST", "contacts", data=payload)
    contact_id = resp["contacts"]["contacts"]["user_id"]

    # Add extra phones via sub-resource (primary phone already set above)
    for phone in extra_phones:
        try:
            _api("POST", f"contacts/{contact_id}/phones", json={
                "phone_number": phone,
                "type": 1,
                "is_primary": False,
            })
            time.sleep(0.1)  # be gentle within a single contact
        except Exception as e:
            # Non-fatal — primary phone already saved
            pass

    return contact_id


def _format_date(d: str) -> str:
    """Convert YYYY-MM-DD → MM/DD/YYYY."""
    try:
        return date.fromisoformat(d).strftime("%m/%d/%Y")
    except (ValueError, TypeError):
        return d or ""


# ── Main entry point ──────────────────────────────────────────────────────────

def push(dry_run: bool = False) -> None:
    """
    Query qualifying contacts from the DB and push them to PhoneBurner.
    """
    today    = date.today()
    date_min = (today + timedelta(days=5)).isoformat()
    date_max = (today + timedelta(days=30)).isoformat()

    with _conn() as con:
        rows = con.execute("""
            SELECT
                l.id AS listing_id,
                p.first_name,
                p.last_name,
                p.phone1, p.phone2, p.phone3, p.phone4, p.phone5,
                l.street,
                l.city,
                l.state,
                l.zip,
                l.sale_date,
                p1.first_name AS primary_first,
                p1.last_name  AS primary_last
            FROM directskip_persons p
            JOIN listings l
              ON l.id = p.listing_id
            LEFT JOIN directskip_persons p1
              ON p1.listing_id = p.listing_id AND p1.person_number = 1
            WHERE l.equity_signal IN ('🏆', '✅')
              AND (l.directskip_date IS NOT NULL AND l.directskip_date != '')
              AND (l.cancelled IS NULL OR LOWER(l.cancelled) != 'yes')
              AND l.sale_date BETWEEN ? AND ?
            ORDER BY l.sale_date ASC, p.listing_id, p.person_number
        """, (date_min, date_max)).fetchall()

    if not rows:
        print("  [PB] No qualifying contacts — nothing to push.")
        return

    print(f"  [PB] {len(rows)} contact(s) qualify.")

    if dry_run:
        print(f"  [PB] [DRY RUN] Would push {len(rows)} contact(s) to PhoneBurner.")
        for r in rows[:5]:
            phones = [p for p in [r["phone1"], r["phone2"], r["phone3"], r["phone4"], r["phone5"]] if p]
            print(f"    {r['first_name']} {r['last_name']} | {r['street']}, {r['city']} | {_format_date(r['sale_date'])} | {len(phones)} phone(s)")
        if len(rows) > 5:
            print(f"    ... and {len(rows) - 5} more")
        return

    # ── Live push ──────────────────────────────────────────────────────────────
    print("  [PB] Fetching account info...")
    member_id = _get_member_id()

    folder_name = f"Eagle Creek {today.isoformat()}"
    folder_id   = _get_or_create_folder(folder_name)

    pushed = 0
    failed = 0

    for i, row in enumerate(rows, 1):
        try:
            contact_user_id = _push_contact(dict(row), member_id, folder_id)
            pushed += 1
            phones = [p for p in [row["phone1"], row["phone2"], row["phone3"], row["phone4"], row["phone5"]] if p]
            primary_phone = phones[0] if phones else ""
            with _conn() as con:
                con.execute(
                    "INSERT OR IGNORE INTO phoneburner_contacts "
                    "(contact_user_id, listing_id, phone, pushed_at) VALUES (?,?,?,?)",
                    (contact_user_id, row["listing_id"], primary_phone, today.isoformat()),
                )
            # Polite rate-limiting — PhoneBurner doesn't publish limits
            # but ~5 req/sec is conservative and safe
            time.sleep(0.2)
        except Exception as e:
            failed += 1
            name = f"{row['first_name'] or ''} {row['last_name'] or ''}".strip()
            print(f"  [PB] ✗ Failed ({name} @ {row['street']}): {e}")

        if i % 25 == 0:
            print(f"  [PB] ... {i}/{len(rows)} processed")

    status = "✓" if not failed else "⚠"
    print(f"  [PB] {status} Done — {pushed} pushed, {failed} failed → folder '{folder_name}'")
